### ISSUE TITLE
App gets stucked in a loop

### ISSUE THREAD

**Issue by andrearot** [DenDmitriev/GrabShot#59]
Hi!

GrabShot is a great idea but it doesn't work on my MacBook Air M1 with Sonoma 14.2  :-(
When i open the app the bars get stucked in a ping-pong loop; if I try to start a video-grab, it does not work.

How can i fix it?

Many thanks!
Andrea

https://github.com/DenDmitriev/GrabShot/assets/5303109/658be1a3-5bd0-4239-913c-fd0aa26b21c5

**Comment by DenDmitriev** [comment]
Hello, andrearot
Progress runs like a standby mode, this is a normal state. If your video doesn't work, it may be unsupported or damaged. You can send me a screen recording video of how this happens for you and it will launch the metadata window by right-clicking on the video item and selecting the Metadata menu.

I’m also currently working on a new version and am ready to add you for Apple Flight testing if you want. This will help me identify errors during development. To do this, send me your Apple ID.
You can try the new interface and perhaps the previous error will go away.

**Comment by andrearot** [comment]
Thank you for you help! I sent my Apple ID to dv.denstr@gmail.com

**Comment by andrearot** [comment]
Hi Denis, I've installed TestFlight and the beta version of GrabShot. I managed to extract pictures from a .mkv file, but I can't do it with .mov which, for what I need to do, is the most important one. 

Are you going to implement .mov support in GrabShot?

<img width="1182" alt="Screenshot 2024-02-06 alle 08 53 38" src="https://github.com/DenDmitriev/GrabShot/assets/5303109/85fb28f5-9947-4691-a699-52e749b800fd">

**Comment by DenDmitriev** [comment]
The application supports mov.
I looked at the screenshot. There may be a problem with the file name. Try removing special characters, there is probably an error in the file name. Name the file RadioRadicale.mov using latin symbols. Please write to me about the result.

**Comment by andrearot** [comment]
Great, it worked! :-)

Thank you for the support. May I suggest you a feature? It would be really helpful if you allow to resize the software window, it's very big to manage on my screen.

All the best to you and your project.

**Comment by DenDmitriev** [comment]
Yes, sure
Send me a video or image of what your window looks like and I will try to simulate it to determine the optimal size.

**Comment by andrearot** [comment]
Great, my resolution is 1280x800:

![Uploading Screenshot 2024-02-06 alle 09.21.05.png…]()

**Comment by andrearot** [comment]
Great, my resolution is 1280x800:
![Screenshot 2024-02-06 alle 09 21 05](https://github.com/DenDmitriev/GrabShot/assets/5303109/84d5c983-0836-4712-86d6-2220d3ba4957)

**Comment by andrearot** [comment]
I also add this: it would be very useful to be able to export the images in lossless .TIF format, so as not to lose quality. Thank you again, and I wish you good work!

**Comment by DenDmitriev** [comment]
Fine. It's not hard to add. Thank you. I'm always happy to receive new proposals.
